name: muchwolf
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b008d'
    - '#76008d'
    - '#67608c'
    - '#713c8c'
    - '#005f8b'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
